### ISSUE TITLE
Another Question

### ISSUE THREAD

**Issue by BlakeFL** [fgervais/project-adafruit-3309-adapter#1]
I really like your esp32 breakout board and was going to order some PCB's from oshpark but realized the pinout for the JST connector did not match most of the USB to Serial adapter boards.  This led me to finding this project. I also like this idea for programming each board via JST instead of needing the extra space on the pcb for USB and the USB to serial chip.  Have you tested the ZH version that goes with your breakout board?  If so I'll order a set of these boards as well.  Thanks for making this project available.  I was thinking of build something very similar until I saw your board shared on OshPark.

**Comment by fgervais** [comment]
I'm glad you like where I'm going with this.

I haven't received the first batch of PCB yet. The ZH version got shipped from OSH Park on Feb 9 so I should get them somewhere in the next 2 weeks.

It has a high chance of first shot success though if you want to risk ordering before I test on my side :).

**Comment by fgervais** [comment]
ZH Adapter: https://oshpark.com/shared_projects/B9to99oI

**Comment by BlakeFL** [comment]
I will wait until you finish your testing.  I am also intrigued by the m2 design and see you're going to try out the new AP63300.

**Comment by fgervais** [comment]
Yes the M.2 form factor is quite nice. Really modern looking. Also feels more premium when inserting. :) However wifi antenna wise, the breadboard version should be better.

I can't wait to try the AP63300. This is the project I'm actively working on. Stay tuned.

**Comment by BlakeFL** [comment]
Once you confirm the 3309 adapter working I'll probably give JLCPCB a try and order the breakout and the breadboard esp32 breakout.

**Comment by fgervais** [comment]
Good idea, I'll report here once I get the PCBs and I'm finish testing them.

**Comment by fgervais** [comment]
It works! 

Just make this adapter and make a straight cable using 2x zhr-6 and 6x ASZHSZH28K152 and it will work. It also looks really clean I think.

I updated the README with the programming section here https://github.com/fgervais/esp32-wrover-breakout and I'll post pictures in this project's README once I have them.

**Comment by BlakeFL** [comment]
Great news. PCB's have been ordered. Unfortunately the 6 pin connector for the ESP32 board and the housings are out of stock on Digikey.  Someone on Amazon sells pre-made cables with connectors though for a bit more money.

**Comment by BlakeFL** [comment]
Got everything soldered but keep getting errors trying to flash the module.  Seems like it doesn't enter boot loader mode.  Any ideas? I've double checked for bridging and made sure components were in the proper place based on kicad.

Error: ESP32: Invalid head of packet (0x69)

**Comment by fgervais** [comment]
Can you read the id with something like so?

```
./esptool.py -p /dev/ttyUSB3 chip_id
```

**Comment by BlakeFL** [comment]
Yeah, I have tried that on mac and windows and get the same Invalid head of packet (0x69) error.  Thing I have checked are... 3.3v supply is good, RST and IO0 are pulled low during serial communication and triple checked for any solder bridging.

esptool.py chip_id
esptool.py v3.0
Found 1 serial ports
Serial port COM3
Connecting........_____....._____....._____....._____....._____....._____....._____
COM3 failed to connect: Failed to connect to Espressif device: Invalid head of packet (0x69)

A fatal error occurred: Could not connect to an Espressif device on any of the 1 available serial ports.

**Comment by fgervais** [comment]
Humm I'm not sure. I've been way too lucky on that one and everything worked first shot on my side so I don't have much experience debugging.

I'm making more of the M.2 version modules this week, I'll let you know if I get failures.

**Comment by BlakeFL** [comment]
Just to confirm placement... is this correct?

[Placement](https://lh3.googleusercontent.com/WLFlV5bqEk_ssBAaA0Iw5iZNFDMvU5Y1Rmtijx3oThuOH3dS0pLpGfZMu_ePlOgWy5CtXqGMMoDHyPfCfE5nyv3wfX-8WRI-g4AuurBqwdUcyLunPI57aVvgsJIqqIvpVAdbqHbyQi0=w2400)

I ordered components for all 3 OshPark boards so I'll probably solder another one up just to make sure I didn't somehow fry the ESP32.

**Comment by fgervais** [comment]
Yes this is correct

**Comment by fgervais** [comment]
Sorry I didn't think people would actually use this board besides me. I'll try to make future ones easier to replicate.

**Comment by BlakeFL** [comment]
Not a problem at all.  Your board is pretty straight forward so it has to be an issue on my end.  I will tinker more with it tonight and let you know.

**Comment by BlakeFL** [comment]
If I manually pull IO0 low then the serial communication works.  Going to see if there is a connection issue between the 3309 adapter and the breakout board.

C:\WINDOWS\system32>esptool.py chip_id
esptool.py v3.0
Found 1 serial ports
Serial port COM3
Connecting....
Detecting chip type... ESP32
Chip is ESP32-D0WD-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 94:b9:7e:7b:f8:0c
Uploading stub...
Running stub...
Stub running...
Warning: ESP32 has no Chip ID. Reading MAC instead.
MAC: 94:b9:7e:7b:f8:0c
Hard resetting via RTS pin...

**Comment by BlakeFL** [comment]
I confirmed during the initial communication with the board, en and IO0 are being set low so it may be getting stuck in reset.  Manually connecting IO0 to ground continues to work and is how I have been uploading code to the device. I have not soldered up another board but will let you know when I do.  Looking online it seems like there is specific timing needed for this but you have the suggested 0.1uf capacitor. I really need to get a oscilloscope which would help with the investigation.

**Comment by fgervais** [comment]
I just put together a new module, however it's the M.2 flavor, but the two designs are really close and this new one works as well.

So for now I successfully tested:

1x breadboard version
2x M.2 version

I'm using esptool version `v2.8-65-gcb2060c` and burning `esp32spiram-idf4-20210202-v1.14.bin`.

**Comment by fgervais** [comment]
I just tried the AP6300 from this project https://github.com/fgervais/project-julie-bed-lights with quite good results.

The worst case I tried was `30v in, 5v out, 1.5A`. This gets the chip to 55C (with ambient being 23.5C) with 382mV of noise (1.27%).

I'm happy about that as this is more than good enough for kind my projects.

**Comment by BlakeFL** [comment]
I'll have to give it a try on a project as well.  I soldered up another ESP32 with your board and this one has no issues with code upload!
